CREATE TABLE IF NOT EXISTS users(name VARCHAR
(200)NOT NULL PRIMARY KEY AUTO_INCREAMENT,
email VARCHAR(200)NOT NULL UNIQUE,phone VARCHAR
(200)NOT NULL,Date VARCHAR (200),Time VARCHAR
(200), Department VARCHAR (200), Symptoms 
VARCHAR (200)NOT NULL)
